import React, { useState, useEffect } from 'react';

const CookieConsent = ({ children }) => {
    const [hasCookieConsent, setHasCookieConsent] = useState(false);

    useEffect(() => {
        const cookieConsent = localStorage.getItem('cookieConsent');
        setHasCookieConsent(cookieConsent === 'true');
    }, []);

    const handleCookieConsent = () => {
        setHasCookieConsent(true);
        localStorage.setItem('cookieConsent', 'true');
    };

    return (
        <>
            {!hasCookieConsent && (
                <div className="cookie-consent fixed-bottom bg-dark text-white p-4 rounded-0 w-50 m-auto">
                    <div className="container">
                        <div className="row">
                            <div className="col-md-10 mb-2 mb-md-0">
                                <p className="m-0">
                                    This form uses AI to generate recommendations. We are not responsible for the content generated by the AI. By continuing, you agree to the use of AI for this purpose.
                                </p>
                            </div>
                            <div className="col-md-2 p-2">
                                <button className="btn btn-sm btn-light" onClick={handleCookieConsent}>
                                    Accept
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            )}
            {hasCookieConsent && children}
        </>
    );
};

export default CookieConsent;
